name: tipitaka_pali
description: Tipitaka Pali Reader

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.6+19

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter # Add this line
  # #enddocregion FlutterLocalizations
  intl: ^0.17.0 # Add this line
  # #enddocregion Intl

  sqflite: ^2.0.0+3
  path: ^1.8.0
  path_provider: ^2.0.2
  shared_preferences: ^2.0.9
  flutter_slidable: ^2.0.0
  provider: ^6.0.0
  substring_highlight: ^1.0.33
  toggle_switch: ^2.0.1
  collection: ^1.15.0
  logger: ^1.0.0
  cupertino_icons: ^1.0.3
  flex_color_scheme: ^6.0.0
  sqflite_common: ^2.0.1+1
  freezed_annotation: ^2.1.0
  sqflite_common_ffi: ^2.0.0+3
  sliding_sheet:
    git:
      url: https://github.com/pndaza/sliding_sheet_bxqm.git
  flutter_typeahead:
    git:
      url: https://github.com/pndaza/flutter_typeahead.git
      ref: 1511c92
  flutter_widget_from_html_core: ^0.8.5+3
  fwfh_text_style: ^2.22.8+1
  styled_text: ^5.1.0
  from_css_color: ^2.0.0
  scrollable_positioned_list: ^0.3.2
  word_selectable_text: ^0.2.0
  multi_split_view: ^2.1.0
  tabbed_view: ^1.13.0+1
  slidable_bar:
    path: packages/slidable_bar
  huge_listview: ^2.0.2
  beautiful_soup_dart: ^0.3.0
  msix: ^2.8.18
  http: ^0.13.5
  internet_connection_checker: ^0.0.1+4
  archive: ^3.3.1
  url_launcher: ^6.1.5
  devicelocale: ^0.5.5
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  build_runner: ^2.1.2

msix_config:
  display_name: Tipitaka Pali Reader
  publisher_display_name: Bhikkhu Sangha
  identity_name: 26554BhikkhuSangha.TipitakaPaliReader 
  publisher: CN=76DA55C6-0663-4AE1-AE5E-609E9823DC18
  msix_version: 1.0.1.0
  store: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true # Add this line
  # #enddocregion Generate

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/database/
    - assets/web/
    - assets/icon/icon.png
    - assets/icon/tpr_dictionary.png

  fonts:
    - family: Pyidaungsu
      fonts:
        - asset: assets/fonts/Pyidaungsu-Regular.ttf
        - asset: assets/fonts/Pyidaungsu-Bold.ttf
    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
        - asset: assets/fonts/NotoSansDevanagari-Bold.ttf
    - family: NotoSansSinhala
      fonts:
        - asset: assets/fonts/NotoSansSinhala-Regular.ttf
        - asset: assets/fonts/NotoSansSinhala-Bold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
